#!/bin/bash
[ ! -e conf ] && cp conf.orig conf || :
source lib/defaults
source conf
#set defaults
PATHS=( "$STORAGE_PATH" "$TMP_PATH" )
FILES=( "$LOG_FILE" )

for dir in $PATHS; do
    [ ! -d "$dir" ] && mkdir "$dir"
done

for file in $FILES; do
    [ ! -e "$file" ] && touch "$file"
done
