#!/bin/bash
[ ! -e conf ] && cp conf.orig conf || :
source lib/defaults
source conf
#set defaults
PATHS=( "$IMAGES_PATH" "$TMP_PATH" "$VIDEOS_PATH" )
FILES=( "$LOG_FILE" )

for dir in ${PATHS[@]}; do
    [ ! -d "$dir" ] && sudo mkdir -p "$dir"
done

sudo touch "$LOG_FILE"
sudo chown $(whoami) "$LOG_FILE"
