#!/bin/bash
__scriptPath="$(cd "$(dirname "$0")"; pwd -P )"
__self="$__scriptPath/$(basename "$0")"
source "$__scriptPath/defaults"
source "$__scriptPath/../conf"

case "$1" in
     "capture" | "timelapse")
        for camera in "${CAMERA_URLS[@]}"; do
            camera_name="${camera%%=*}"
            camera_url="${camera#*=}"
            if [[ "$1" == capture ]]; then
            	"$__scriptPath/image_capture" -n "$camera_name" "$camera_url"
            elif [[ "$1" == timelapse ]]; then
                #This weeks progress
                "$__scriptPath/make_timelapse" -d 7 "$camera_name"
                #From the start of time
                "$__scriptPath/make_timelapse" -s 01/01/2000 -o "$camera_name" "$cammera_name"
            fi
        done
        ;;
    email )
        "$__scriptPath/send_email"
        ;;
    job )
        ( 
	crontab -l 2>/dev/null
	cat <<-JOB
		$CAPTURE_FREQ $__self capture
		$TIMELAPSE_FREQ $__self timelapse
		$EMAIL_FREQ $__self email
	JOB
	) | crontab -
esac
