#!/bin/bash
__scriptPath="$(cd "$(dirname "$0")"; pwd -P )"
__self="$__scriptPath/$(basename "$0")"
source "$__scriptPath/defaults"
source "$__scriptPath/../conf"

case "$1" in
     "capture" | "timelapse")
        for camera in "${CAMERA_URLS[@]}"; do
            cameraName="${camera%%=*}"
            cameraUrl="${camera#*=}"
	    log="$__scriptPath/../logs/$camera_name\ make_timelapse\ $(date +%m-%d-%Y).log"
            if [[ "$1" == capture ]]; then
            	"$__scriptPath/image_capture" -n "$cameraName" "$cameraUrl"
            elif [[ "$1" == timelapse ]]; then
                #This weeks progress
                "$__scriptPath/make_timelapse" -d 7 "$cameraName"
                #From the start of time
		#echo $(( $(ls $__scriptPath/../$IMAGES_PATH | wc -l )/ ${#CAMERA_URLS[@]}/60 ))  ;
                "$__scriptPath/make_timelapse" \
			-f $(( $( ls $__scriptPath/../$IMAGES_PATH | wc -l ) / ${#CAMERA_URLS[@]} / 60 ))\
			-s 01/01/2000 \
			-e $(date +%m/%d/%Y)\
			-o "$cameraName"\
			"$cammeraName" 

		#scp $STORAGE_ID "$__scriptPath/../$VIDEOS_PATH/$cameraName.mp4" $STORAGE_SERVER:$STORAGE_LOCATION
            fi
        done
        ;;
    email )
        "$__scriptPath/send_email"
        ;;
    job )
        ( 
	crontab -l 2>/dev/null
	cat <<-JOB
		$CAPTURE_FREQ $__self capture
		$TIMELAPSE_FREQ $__self timelapse
		$EMAIL_FREQ $__self email
	JOB
	) | crontab -
esac
