#!/bin/bash
__scriptVersion=1.0
__scriptPID=$$
__scriptPath="$(cd "$(dirname "$0")"; pwd -P )"
__scriptFile="$(basename "$0")"

# Function ===================================================================== 
#           Name:  date_range
#         Author:  Rusty Gibbs 
#       Homepage:  http://www.wickedidol.com
#            Git:  https://github.com/fenchurch/TimeLapse.git
#        Created:  2019-02-02
#       Modified:  2019-02-08
# ==============================================================================
usage="usage:
    $__scriptFile <Start Date in MM/DD/YYYY format> [End Date optional]"
# default vars =============================================================={{{

# ===========================================================================}}}
source ./defaults
source ../conf
main(){
    start_m=$(cut -d"/" -f1 <<< $1)
    start_d=$(cut -d"/" -f2 <<< $1)
    start_y=$(cut -d"/" -f3 <<< $1)
    touch -t ${start_y}${start_m}${start_d}0000 ts-start
    start="-newer ts-start "
    if [[ "$2" != "" ]]; then
        end_m=$(cut -d "/" -f1 <<< $2)
        end_d=$(cut -d"/" -f2 <<< $2)
        end_y=$(cut -d"/" -f3 <<< $2)
        touch -t ${end_y}${end_m}${end_d}2359 ts-end
        end="! -newer ts-end "
    fi 
    find $(realpath "$STORAGE_PATH") -type f $start $end -exec echo {} ";"
    rm ts-start ts-end
}
if [[ $# -eq 0 ]]; then
    echo "$usage"
    exit 1
fi
main "$1" "${2:-}"
