#!/bin/bash
__scriptVersion=1.0
__scriptPID=$$
__scriptPath="$(cd "$(dirname "$0")"; pwd -P )"
__scriptFile="$(basename "$0")"

# Function ===================================================================== 
#           Name:  date_range
#         Author:  Rusty Gibbs 
#       Homepage:  http://www.wickedidol.com
#            Git:  https://github.com/fenchurch/TimeLapse.git
#        Created:  2019-02-02
#       Modified:  2019-02-08
# ==============================================================================
usage="usage:
    $__scriptFile <Start Date in MM/DD/YYYY format> [End Date optional]"
# default vars =============================================================={{{

# ===========================================================================}}}
source $__scriptPath/defaults
source $__scriptPath/../conf
main(){
    start_m=$(cut -d"/" -f1 <<< $1)
    start_d=$(cut -d"/" -f2 <<< $1)
    start_y=$(cut -d"/" -f3 <<< $1)
    [[ ${#start_m} == 1 ]] && start_m=0$start_m
    [[ ${#start_d} == 1 ]] && start_d=0$start_d
    [[ ${#start_y} == 1 ]] && start_y=0$start_y
    touch -t ${start_y}${start_m}${start_d}0000 start

    start="-newer start "
    if [[ "$2" != "" ]]; then
        end_m=$(cut -d "/" -f1 <<< $2)
        end_d=$(cut -d"/" -f2 <<< $2)
        end_y=$(cut -d"/" -f3 <<< $2)
        [[ ${#end_m} == 1 ]] && end_m=0$end_m
        [[ ${#end_d} == 1 ]] && end_d=0$end_d
        [[ ${#end_y} == 2 ]] && end_y=20$end_y
        touch -t ${end_y}${end_m}${end_d}2359 end
    else
        touch -t $(date +%Y%m%d2359) end
    fi 
    end="! -newer end "
    find $(realpath "$__scriptPath/../$STILLS_PATH") -type f $start $end -exec echo {} ";" | sort
    rm start end
}
if [[ $# -eq 0 ]]; then
    echo "$usage"
    exit 1
fi
main "$1" "${2:-}"
